TenantMNG/Controllers/PMController.cs
using log4net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TenantMNG.ADO.NET;
using TenantMNG.BAL;
using TenantMNG.Core;
using TenantMNG.Models;
using TenantMNG.ViewModel;
using PagedList;
using System.Data;
using System.Web.UI.WebControls;
using System.Collections;
using System.Web.Helpers;
using System.Web.Script.Serialization;
using System.Globalization;
using System.Web;
using System.IO;
using System.Web.UI;
using Ionic.Zip;
using System.Data.SqlClient;
using System.Configuration;
using System.Text;
using Newtonsoft.Json.Linq;

namespace TenantMNG.Controllers
{
    public class PMController : MyController
    {
        // GET: User
        DB_TenantMNGEntities _dbc = new DB_TenantMNGEntities();
        ILog log = log4net.LogManager.GetLogger(typeof(PMController));
        UdisEntities _dmeter = new UdisEntities();



        // GET: PM
        [SessionCheck]
        public ActionResult Dashboard()
        {
            int pmid = Convert.ToInt32(Session["uid"].ToString());

            var _user = _dbc.tbl_user_master.Where(x => x.int_user_type_id == 3 && x.int_pm_id == pmid).ToList().Take(5).OrderByDescending(x => x.int_id);

            var _invoice = _dbc.tbl_invoice.Where(x => x.tbl_user_master.int_pm_id == pmid).ToList().Take(5).OrderByDescending(x => x.int_invoice_id);

            PMDashboardVM _objvm = new PMDashboardVM();

            _objvm.tbl_invoice = _invoice.ToList();

            _objvm.tbl_user_master = _user.ToList();

            bindDropBox();
            return View(_objvm);
        }

        public ActionResult ChangePassword()
        {
            int _id = Convert.ToInt32(Session["uid"].ToString());
            var _user = _dbc.tbl_user_master.Where(x => x.int_id == _id).FirstOrDefault();

            UserMasterVM vmobj = new UserMasterVM()
            {

                int_id = _id,
                str_password = _user.str_password,


            };


            return View(vmobj);
        }

        [SessionCheck]
        public ActionResult Tenant(int? page)
        {
            int pmid = Convert.ToInt32(Session["uid"].ToString());
            return View(_dbc.tbl_user_master.Where(x => x.int_user_type_id == 3 && x.int_pm_id == pmid).ToList().ToPagedList(page ?? 1, CommonCls._pagesize));
        }

        [SessionCheck]
        [HttpGet] // this action result returns the partial containing the modal
        public ActionResult AssignMeter(int id)
        {
            try
            {

                var _tenant = _dbc.tbl_tenant_contract.Where(x => x.int_tenant_id == id).SingleOrDefault();

                UdisEntities _dbmeter = new UdisEntities();

                var _meter = _dbmeter.UDIS.Select(m => m.CFE_MeterID).Distinct().ToList();

                var _tenantmeter = _dbc.tbl_tenant_meter.Where(x => x.int_tenant_id == id && x.bit_is_assign == true).ToList();

                TenantMeterVM _objvm = new TenantMeterVM();

                _objvm.Meters = getMeters();


                if (_tenantmeter != null)
                {
                    foreach (var meter in _objvm.Meters)
                    {
                        var test = _tenantmeter.Where(x => x.str_meter_id == meter.Text).SingleOrDefault();

                        if (test != null)
                            meter.Selected = true;

                    }

                }



                _objvm.bit_is_assign = true;
                _objvm.int_tenant_id = id;

                ViewBag.messgVal = 2;


                return View(_objvm);
            }
            catch (Exception ex)
            {
                log.Error(ex.Message);
            }
            return View();


        }

        [HttpPost] // this action result returns the partial containing the modal
        public ActionResult AssignMeter(TenantMeterVM _objvm)
        {


            int _lval = 0;
            try
            {
                TenantBAL objbal = new TenantBAL();


                objbal.tenant_delete_meter(_objvm.int_tenant_id);

                foreach (var meterid in _objvm.Meters)
                {
                    if (meterid.Selected)
                    {
                        //int mid = 0;
                        objbal = new TenantBAL();
                        _objvm.bit_is_assign = true;
                        //_objvm.str_meter_id = Int32.TryParse(meterid.Value, out mid) ? Int32.Parse(meterid.Value) : (int?)null;
                        _objvm.str_meter_id = meterid.Text;
                        _objvm.multiplier = 1;
                        _lval = objbal.tenant_meter_insert(_objvm);
                    }

                }

                ViewBag.messgVal = _lval;
            }
            catch (Exception ex)
            {
                log.Error(ex.Message);
            }
            return RedirectToAction("Tenant");
        }

        [HttpGet] // this action result returns the partial containing the modal
        public ActionResult DetachMeter(string id)
        {
            Session["tenant_id"] = id;
            Session["meter_id"] = id;
            return new EmptyResult();
        }

        [HttpPost] // this action result returns the partial containing the modal
        public ActionResult DetachMeter()
        {
            TenantBAL objbal = new TenantBAL();

            int _id = Convert.ToInt32(Session["tenant_id"].ToString());

            int _lVal = objbal.tenant_detach_meter(_id);


            return RedirectToAction("Tenant");
        }

        [HttpGet] // this action result returns the partial containing the modal
        public ActionResult DeleteInvoice(string id)
        {
            Session["invoice_id"] = id;
            return new EmptyResult();
        }

        [HttpPost] // this action result returns the partial containing the modal
        public ActionResult DeleteInvoice()
        {
            UserBAL usrbal = new UserBAL();

            int _id = Convert.ToInt32(Session["invoice_id"].ToString());

            int _lVal = usrbal.invoice_delete(_id);


            return RedirectToAction("TenantActivity");
        }


        [HttpPost] // this action result returns the partial containing the modal
        public ActionResult DetachMeterTenant()
        {
            TenantBAL objbal = new TenantBAL();

            //int _meterid = Convert.ToInt32(Session["meter_id"].ToString());
            string _meterid = Session["meter_id"].ToString();
            var _meter = _dbc.tbl_tenant_meter.Where(x => x.str_meter_id == _meterid && x.bit_is_assign == true).SingleOrDefault();
            int _lVal = objbal.tenant_detach_meter_tenant(_meter.int_tenant_id, _meterid);
            return RedirectToAction("Meters");
        }

        [SessionCheck]
        [HttpGet]
        public ActionResult CreateInvoice(string strmeterid)
        {
            InvoiceVM _objvm = new InvoiceVM();
            try
            {
                int id = 0;

                var _tenantid = _dbc.tbl_tenant_meter.Where(x => x.str_meter_id == strmeterid && x.bit_is_assign == true).FirstOrDefault();
                var tarifas = _dbc.tbl_tarifas.FirstOrDefault();

                if (_tenantid != null)
                {
                    _objvm.int_invoice_id = 0;
                    id = Convert.ToInt32(Convert.ToInt32(_tenantid.int_tenant_id));

                    //var _tenantbillinginfo = _dbc.tbl_tenant_billing_info.Where(x => x.int_tenant_id == id).SingleOrDefault();
                    /*var _ratesinfo = _dbc.tbl_tarifas.FirstOrDefault();

                    if (_ratesinfo != null)
                    {
                        _objvm.suministro = _ratesinfo.suministro;
                        _objvm.distribucion = _ratesinfo.distribucion;
                        _objvm.tarifa_transmision = _ratesinfo.tarifa_transmision;
                        _objvm.operacion_cenace = _ratesinfo.operacion_cenace;
                        _objvm.dec_base_rate = _ratesinfo.dec_base_rate;
                        _objvm.dec_inter_energy_rate = _ratesinfo.dec_inter_energy_rate;
                        _objvm.dec_peak_energy_rate = _ratesinfo.dec_peak_energy_rate;
                        _objvm.capacidad = _ratesinfo.capacidad;
                        _objvm.cre_servicios_conexos = _ratesinfo.cre_servicios_conexos;

                    }*/
                    int _uid = Convert.ToInt32(Session["uid"].ToString());
                    var _pmbillingtime = _dbc.tbl_pm_billing_hours.Where(x => x.int_pm_id == _uid).SingleOrDefault();
                    if (_pmbillingtime != null /*&& _ratesinfo != null*/)
                    {

                        _objvm.str_inter_e_time = _pmbillingtime.str_inter_e_time_1_m;
                        _objvm.str_inter_s_time = _pmbillingtime.str_inter_s_time_2_m;

                        _objvm.str_peak_e_time = _pmbillingtime.str_peak_e_time_m;
                        _objvm.str_peak_s_time = _pmbillingtime.str_peak_s_time_m;

                        //_objvm.int_invoice_period = _tenantbillinginfo.tbl_user_master.int_invoice_period;
                        _objvm.int_invoice_period = 3;
                    }

                    if (tarifas != null)
                    {
                        var _tarifasvm = new TarifasVM();

                        _tarifasvm.dec_base_rate = tarifas.dec_base_rate;
                        _tarifasvm.dec_inter_energy_rate = tarifas.dec_inter_energy_rate;
                        _tarifasvm.dec_peak_energy_rate = tarifas.dec_peak_energy_rate;
                        _tarifasvm.suministro = tarifas.suministro;
                        _tarifasvm.distribucion = tarifas.distribucion;
                        _tarifasvm.tarifa_transmision = tarifas.tarifa_transmision;
                        _tarifasvm.operacion_cenace = tarifas.operacion_cenace;
                        _tarifasvm.capacidad = tarifas.capacidad;

TenantMNG/Views/Admin/ChangePassword.cshtml
@model TenantMNG.ViewModel.UserMasterVM
@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="content-header">
    <div id="breadcrumb"> <a href="@Url.Action("Dashboard", "Admin")" title="Go to Home" class="tip-bottom"><i class="icon-home"></i>@TenantMNG.Resource.home</a> <a href="#" class="tip-bottom">Account</a> <a href="#" class="current">@TenantMNG.Resource.changepassword</a> </div>

</div>
<div class="container-fluid">

    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>@TenantMNG.Resource.changepassword</h5>
                </div>
                <div class="widget-content nopadding">
                    @Html.Partial("~/Views/Shared/_ChangPassword.cshtml", Model)
                </div>
            </div>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")

TenantMNG/Views/Admin/Dashboard.cshtml
@model TenantMNG.ViewModel.AdminDashboard

@{
    ViewBag.Title = TenantMNG.Core.CommonCls._applicationname + " : Dashboard";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div id="content-header">
    <div id="breadcrumb"> <a href=@Url.Action("Dashboard", "Admin") title="Go to Home" class="tip-bottom">
<img src="~/img/icons/16/home.png" /> @TenantMNG.Resource.home</a> <a href="#" class="current">@TenantMNG.Resource.dashboard</a>  </div>

</div>
<div class="container-fluid">

    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"><i class="icon-dashboard"></i></span>
                    <h5>@TenantMNG.Resource.dashboard</h5>
                </div>
                <div class="widget-content">
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="widget-box">
                                <div class="widget-title">
                                    <span class="icon"><i class="icon-list"></i></span>
                                    <h5>@TenantMNG.Resource.pm_list</h5>
                                </div>
                                <div class="widget-content nopadding updates">

                                    @foreach (var user in Model.tbl_PM)
                                    {

                                        <div class="new-update clearfix">

                                            <div class="update-done">
                                                <strong>
                                                    @Html.ActionLink(user.str_comp_name, "Edit", "User", new { @id = user.int_id }, null)

                                                </strong>
                                            </div>
                                            @*<div class="update-date">@TenantMNG.Core.CommonCls.getMeterName(user.int_id)</div>
                    <div class="update-date"><span class="update-day">20</span>jan</div>*@
                                        </div>
                                    }

                                    <ul class="recent-posts">
                                        <li>
                                            @if (Model.tbl_PM.ToList().Count > 0)
                                            {
                                                @Html.ActionLink(TenantMNG.Resource.view_all, "PropertyManager", "User", null, new { @class = "btn btn-warning btn-mini" })
                                                @*<button class="btn btn-warning btn-mini">View All</button>*@
                                            }
                                            else
                                            {
                                                <i> @TenantMNG.Resource.sorry_mess</i>
                                            }
                                        </li>
                                    </ul>
                                </div>
                                <div class="widget-title">
                                    <span class="icon">  <img src="~/img/icons/16/piechart.png" /> </span>
                                    <h5>@TenantMNG.Resource.tenantEngcon</h5>
                                </div>
                                <div id="container" style="min-width: 310px; height: 300px; max-width: 600px; margin: 0 auto"></div>
                            </div>
                        </div>


                        <div class="span6">
                            <div class="widget-box">
                                <div class="widget-title">
                                    <span class="icon"><i class="icon-list"></i></span>
                                    <h5>@TenantMNG.Resource.tenant_list</h5>
                                </div>
                                <div class="widget-content nopadding updates">

                                    @foreach (var user in Model.tbl_Tenant)
                                    {

                                        <div class="new-update clearfix">

                                            <div class="update-done">
                                                <strong>
                                                    @Html.ActionLink(user.str_comp_name, "EditTenant", "User", new { @tenantid = user.int_id }, null)
                                                </strong>
                                            </div>
                                            <div class="update-date">@TenantMNG.Core.CommonCls.getMeterName(user.int_id)</div>
                                            @*<div class="update-date"><span class="update-day">20</span>jan</div>*@
                                        </div>
                                    }
                                    <ul class="recent-posts">
                                        <li>
                                            @if (Model.tbl_Tenant.ToList().Count > 0)
                                            {
                                                @Html.ActionLink(TenantMNG.Resource.view_all, "Tenant", "User", null, new { @class = "btn btn-warning btn-mini" })
                                                @*<button class="btn btn-warning btn-mini">View All</button>*@
                                            }
                                            else
                                            {
                                                <i> @TenantMNG.Resource.sorry_mess</i>
                                            }


                                        </li>
                                    </ul>

                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



@section scripts{

    <script type="text/javascript" src="https://code.highcharts.com/highcharts.js"></script>
    <script type="text/javascript" src="https://code.highcharts.com/modules/exporting.js"></script>
    <script type="text/javascript" src="https://code.highcharts.com/modules/export-data.js"></script>
    <script>

            $(function () {
                const tenetsNames = [];
                var dataPoints = [];
                var options = {};
                options.url = '@Url.Action("TenantconsumptionReportNEW", "PM")';
                options.data = { int_id:null, page: null, sortBy: null, s_date: null, tenantid: null, };
                options.type = "GET";
                options.contentType = 'application/json; charset=utf-8';
                options.dataType = "json";
                options.success = function (datajson) {
                    debugger;
                    var series = new Array();
                    for (var i in datajson) {
                        var serie = new Array(datajson[i].Name, datajson[i].totalenergy);
                        series.push(serie);
                    }
                    DrawPieChart(series);
                };
                options.error = function () {
                    alert('error');
                };
                $.ajax(options);
            });

            $(function () {
                $("#ddl_tenant").change(function () {
                    var options = {};
                    options.url = '@Url.Action("TenantconsumptionReportNEW", "PM")';
                    options.data = { int_id: null, page: null, sortBy: null, s_date: null, tenantid: null, };
                options.type = "GET";
                options.contentType = 'application/json; charset=utf-8';
                options.dataType = "json";
                options.success = function (datajson) {
                    debugger;
                    var series = new Array();
                    for (var i in datajson) {
                        var serie = new Array(datajson[i].Name, datajson[i].totalenergy);
                        series.push(serie);
                    }
                    DrawPieChart(series);

                };
                options.error = function () {
                    alert('error');
                };
                $.ajax(options);
                });
            });

            function DrawPieChart(series) {
                debugger;

                Highcharts.chart('container', {
                    chart: {
                        plotBackgroundColor: null,
                        plotBorderWidth: null,
                        plotShadow: false,
                        type: 'pie'
                    },
                    title: {
                        text: 'Consumo de Inquilinos'
                    },
                    tooltip: {
                        pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                    },
                    plotOptions: {
                        pie: {
                            allowPointSelect: true,
                            cursor: 'pointer',
                            dataLabels: {
                                enabled: true,
                                format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                                style: {
                                    color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                                }
                            }
                        }
                    },

                    series: [{

                        name: 'Share',
                        data: series

                    }]
                });
            }
    </script>
}

TenantMNG/Views/Admin/Profile.cshtml
@model TenantMNG.ViewModel.UserMasterVM
@{
    ViewBag.Title = "Profile";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="content-header">
    <div id="breadcrumb"> <a href="@Url.Action("Dashboard", "Admin")" title="Go to Home" class="tip-bottom"><i class="icon-home"></i> Home</a> <a href="#" class="tip-bottom">Account</a> <a href="#" class="current">Change Profile</a> </div>

</div>
<div class="container-fluid">

    <div class="row-fluid">
        <div class="span12">
            <div class="widget-box">
                <div class="widget-title">
                    <span class="icon"> <i class="icon-align-justify"></i> </span>
                    <h5>Change Profile</h5>
                </div>
                <div class="widget-content nopadding">
                    @Html.Partial("~/Views/Shared/_Profile.cshtml", Model)
                </div>
            </div>
        </div>
    </div>
</div>
@Scripts.Render("~/bundles/jqueryval")